### ISSUE TITLE
添加完图片报错

### ISSUE THREAD

**Issue by yangqb** [yechaoa/PictureSelectorDemo#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: lease.drive.com.drivelease, PID: 11487
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{lease.drive.com.drivelease/com.yalantis.ucrop.PictureMultiCuttingActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class android.support.v7.widget.Toolbar
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5019)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class android.support.v7.widget.Toolbar
                      at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

**Comment by yechaoa** [comment]
控件有问题，Toolbar，看一下是不是转换不对
